objects/Account.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AlternativePhone__c</fullName>
        <label>AlternativePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DoNotCall__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DoNotCall</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HomeNumbers__c</fullName>
        <label>HomeNumber</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <label>MaritalStatus</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OfficeNumber__c</fullName>
        <label>OfficeNumber</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VIP</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>CaseNumber__c</fullName>
        <label>CaseNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseOrigin__c</fullName>
        <label>CaseOrigin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <label>SubType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Policy__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Policys</relationshipLabel>
        <relationshipName>Policys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Policy_Status__c</fullName>
        <label>Policy_Status</label>
        <picklist>
            <picklistValues>
                <fullName>Policy In Force</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Policy Lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Declined/Incomplete</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Policy_Type__c</fullName>
        <label>Policy_Type</label>
        <picklist>
            <picklistValues>
                <fullName>ILP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Traditional Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Related</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountDetail.cls
public with sharing class AccountDetail {
// Phuc
	public class Data {
		@AuraEnabled
		public Account objAccount { get; set; }

		@AuraEnabled
		public List<Case> lstCase { get; set; }	

		@AuraEnabled
		public Map<String, String> policyMap {get;set;}
		
	}
	/* Test Deploy*/
	/* I am Super Man =]]]*/

	/*Phuc LONG*/
	/*
	 * prepare
	 * @param: objId
	 * @return: tag
	 * @created: 20/07/2017 Nguyen Hoang Khoi
	 * @modified: 
	 */
	@AuraEnabled
	public static AccountDetail.Data getDataView(String objId){
		AccountDetail.Data tag = new AccountDetail.Data();
		try{
			String sqlAccount = '';
			tag.objAccount = Database.query('Select id,email__c,CreatedDate ,Name,Gender__c,MaritalStatus__c,Age__c,Birthdate__c,Phone,AlternativePhone__c,HomeNumbers__c,OfficeNumber__c,DoNotCall__c,VIP__c from Account  where Id =: objId');
			tag.lstCase =  Database.query('select id,SubType__c,CaseOrigin__c,CaseNumber__c,CreatedDate from Case where account.ID =: objId');
			
			List<Policy__c> lstPolicy = Database.query('select id, Account__c, Policy_Status__c, Policy_Type__c from Policy__c Where Account__c =: objId');
			/*Traditional Life*/
			Integer traditionalLapsed = 0;
			Integer traditionalForce = 0;
			Integer traditionalProgress = 0;
			Integer traditionalIncomplete = 0;
			/*ILp*/
			Integer ilpLapsed = 0;
			Integer ilpForce = 0;
			Integer ilpProgress = 0;
			Integer ilpIncomplete = 0;
			/*Credit*/
			Integer creditLapsed = 0;
			Integer creditForce = 0;
			Integer creditProgress = 0;
			Integer creditIncomplete = 0;
			for(Policy__c obj : lstPolicy){
				/*Set number Traditional Life*/
				if(obj.Policy_Type__c == 'Traditional Life'){
					if(obj.Policy_Status__c == 'Policy Lapsed'){
						traditionalLapsed = traditionalLapsed + 1;
					}
					if(obj.Policy_Status__c == 'Policy In Force'){
						traditionalForce = traditionalForce + 1;
					}
					if(obj.Policy_Status__c == 'Application In Progress'){
						traditionalProgress = traditionalProgress + 1;
					}
					if(obj.Policy_Status__c == 'Application Declined/Incomplete'){
						traditionalIncomplete = traditionalIncomplete + 1;
					}
				}
				/*Set number ILP*/
				if(obj.Policy_Type__c == 'ILP'){
					System.debug('xxxx ILP');
					if(obj.Policy_Status__c == 'Policy Lapsed'){
						ilpLapsed = ilpLapsed + 1;
					}
					if(obj.Policy_Status__c == 'Policy In Force'){
						ilpForce = ilpForce + 1;
					}
					if(obj.Policy_Status__c == 'Application In Progress'){
						ilpProgress = ilpProgress + 1;
					}
					if(obj.Policy_Status__c == 'Application Declined/Incomplete'){
						ilpIncomplete = ilpIncomplete + 1;
					}
				}
				/*Set number Credit Related*/
				if(obj.Policy_Type__c.equals('Credit Related')){
					System.debug('xxxx Credit');
					if(obj.Policy_Status__c == 'Policy Lapsed'){
						creditLapsed = creditLapsed + 1;
					}
					if(obj.Policy_Status__c == 'Policy In Force'){
						creditForce = creditForce + 1;
					}
					if(obj.Policy_Status__c == 'Application In Progress'){
						creditProgress = creditProgress + 1;
					}
					if(obj.Policy_Status__c == 'Application Declined/Incomplete'){
						creditIncomplete = creditIncomplete + 1;
					}
				}
			}

			tag.policyMap = new Map<String, String>();
			tag.policyMap.put('traditionalLapsed', String.valueOf(traditionalLapsed));
			tag.policyMap.put('traditionalForce', String.valueOf(traditionalForce));
			tag.policyMap.put('traditionalProgress', String.valueOf(traditionalProgress));
			tag.policyMap.put('traditionalIncomplete', String.valueOf(traditionalIncomplete));
			
			tag.policyMap.put('ilpLapsed', String.valueOf(ilpLapsed));
			tag.policyMap.put('ilpForce', String.valueOf(ilpForce));
			tag.policyMap.put('ilpProgress', String.valueOf(ilpProgress));
			tag.policyMap.put('ilpIncomplete', String.valueOf(ilpIncomplete));
			
			tag.policyMap.put('creditLapsed', String.valueOf(creditLapsed));
			tag.policyMap.put('creditForce', String.valueOf(creditForce));
			tag.policyMap.put('creditProgress', String.valueOf(creditProgress));
			tag.policyMap.put('creditIncomplete', String.valueOf(creditIncomplete));
		}catch(Exception ex){
			System.debug('xxxxx ' + ex.getMessage());
		}

		return tag;
	}
}