objects/Account.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AlternativePhone__c</fullName>
        <label>AlternativePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DoNotCall__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DoNotCall</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HomeNumbers__c</fullName>
        <label>HomeNumber</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>MaritalStatus__c</fullName>
        <label>MaritalStatus</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OfficeNumber__c</fullName>
        <label>OfficeNumber</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VIP</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>CaseNumber__c</fullName>
        <label>CaseNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseOrigin__c</fullName>
        <label>CaseOrigin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <label>SubType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Policy__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Policys</relationshipLabel>
        <relationshipName>Policys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Policy_Status__c</fullName>
        <label>Policy_Status</label>
        <picklist>
            <picklistValues>
                <fullName>Policy In Force</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Policy Lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Declined/Incomplete</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Policy_Type__c</fullName>
        <label>Policy_Type</label>
        <picklist>
            <picklistValues>
                <fullName>ILP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Traditional Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Related</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/VisionAccountController.cls
public with sharing class VisionAccountController {

	public class Data {
		@AuraEnabled
		public Account objAccount { get; set; }

		@AuraEnabled
		public List<Case> lstCase { get; set; }

		@AuraEnabled
		public Map<String,Map<String,Integer>> mapPolicyAura {get;set;}

		@AuraEnabled
		public Integer traditionalLapsed {get;set;}

		@AuraEnabled
		public Integer traditionalForce {get;set;}

		@AuraEnabled
		public Integer traditionalProgress {get;set;}

		@AuraEnabled
		public Integer traditionalIncomplete {get;set;}

		@AuraEnabled
		public Integer ilpLapsed {get;set;}

		@AuraEnabled
		public Integer ilpForce {get;set;}

		@AuraEnabled
		public Integer ilpProgress {get;set;}

		@AuraEnabled
		public Integer ilpIncomplete {get;set;}

		@AuraEnabled
		public Integer creditLapsed {get;set;}

		@AuraEnabled
		public Integer creditForce {get;set;}

		@AuraEnabled
		public Integer creditProgress {get;set;}

		@AuraEnabled
		public Integer creditIncomplete {get;set;}

		@AuraEnabled
		public Map<String,String> mapTest {get;set;}

		@AuraEnabled
		public Integer litCaseNumber {get;set;}
	}

	/*
	 * prepare
	 * @param: objId
	 * @return: tag
	 * @created: 20/07/2017 Nguyen Hoang Khoi
	 * @modified: 
	 */
	@AuraEnabled
	public static VisionAccountController.Data getDataView(String objId){
		VisionAccountController.Data tag = new VisionAccountController.Data();
		try{
			String sqlAccount = '';
			tag.objAccount = Database.query('Select id,email__c,CreatedDate ,Name,Gender__c,MaritalStatus__c,Age__c,Birthdate__c,Phone,AlternativePhone__c,HomeNumbers__c,OfficeNumber__c,DoNotCall__c,VIP__c from Account  where Id =: objId');
			tag.lstCase =  Database.query('select id,SubType__c,CaseOrigin__c,CaseNumber__c,CreatedDate from Case where account.ID =: objId');
			tag.litCaseNumber = tag.lstCase.size();
			List<Policy__c> lstPolicy = Database.query('select id, Account__c, Policy_Status__c, Policy_Type__c from Policy__c Where Account__c =: objId');
			/*Traditional Life*/
			tag.traditionalLapsed = 0;
			tag.traditionalForce = 0;
			tag.traditionalProgress = 0;
			tag.traditionalIncomplete = 0;
			/*ILp*/
			tag.ilpLapsed = 0;
			tag.ilpForce = 0;
			tag.ilpProgress = 0;
			tag.ilpIncomplete = 0;
			/*Credit*/
			tag.creditLapsed = 0;
			tag.creditForce = 0;
			tag.creditProgress = 0;
			tag.creditIncomplete = 0;
			for(Policy__c obj : lstPolicy){
				/*Set number Traditional Life*/
				if(obj.Policy_Type__c != null && obj.Policy_Status__c != null){
					if(obj.Policy_Type__c == 'Traditional Life'){
						if(obj.Policy_Status__c == 'Policy Lapsed'){
							tag.traditionalLapsed = tag.traditionalLapsed + 1;
						}
						if(obj.Policy_Status__c == 'Policy In Force'){
							tag.traditionalForce = tag.traditionalForce + 1;
						}
						if(obj.Policy_Status__c == 'Application In Progress'){
							tag.traditionalProgress = tag.traditionalProgress + 1;
						}
						if(obj.Policy_Status__c == 'Application Declined/Incomplete'){
							tag.traditionalIncomplete = tag.traditionalIncomplete + 1;
						}
					}
					/*Set number ILP*/
					if(obj.Policy_Type__c == 'ILP'){
						System.debug('xxxx ILP');
						if(obj.Policy_Status__c == 'Policy Lapsed'){
							tag.ilpLapsed = tag.ilpLapsed + 1;
						}
						if(obj.Policy_Status__c == 'Policy In Force'){
							tag.ilpForce = tag.ilpForce + 1;
						}
						if(obj.Policy_Status__c == 'Application In Progress'){
							tag.ilpProgress = tag.ilpProgress + 1;
						}
						if(obj.Policy_Status__c == 'Application Declined/Incomplete'){
							tag.ilpIncomplete = tag.ilpIncomplete + 1;
						}
					}
					/*Set number Credit Related*/
					if(obj.Policy_Type__c.equals('Credit Related')){
						System.debug('xxxx Credit');
						if(obj.Policy_Status__c == 'Policy Lapsed'){
							tag.creditLapsed = tag.creditLapsed + 1;
						}
						if(obj.Policy_Status__c == 'Policy In Force'){
							tag.creditForce = tag.creditForce + 1;
						}
						if(obj.Policy_Status__c == 'Application In Progress'){
							tag.creditProgress = tag.creditProgress + 1;
						}
						if(obj.Policy_Status__c == 'Application Declined/Incomplete'){
							tag.creditIncomplete = tag.creditIncomplete + 1;
						}
					}
				}
			}
			/*End Sa*/
			tag.mapTest = new Map<String,String>();
			tag.mapTest.put('key1', 'Value');
			tag.mapTest.put('key2', 'Value');
			tag.mapTest.put('key3', 'Value');
		}catch(Exception ex){
			System.debug('xxxxx ' + ex.getMessage());
		}

		return tag;
	}
}

/*List<Policy__c> lstPolicy = [select id, Account__c, Policy_Status__c, Policy_Type__c from Policy__c Where Account__c='0012800000WAlmLAAT'];
Map<String, Map<String, Integer>> mapPolicy = new Map<String, Map<String, Integer>>();
for(Policy__c p : lstPolicy){
	if(!mapPolicy.containsKey(p.Policy_Type__c)){
		Map<String, Integer> mapByStatus = new Map<String, Integer>();
		mapByStatus.put(p.Policy_Status__c, 1);
		mapPolicy.put(p.Policy_Type__c, mapByStatus);
	}else{
		//mapPolicy.get(p.Policy_Type__c) 
		if(mapPolicy.get(p.Policy_Type__c).containsKey(p.Policy_Status__c)){
			Integer countNuber = mapPolicy.get(p.Policy_Type__c).get(p.Policy_Status__c) + 1;
			mapPolicy.get(p.Policy_Type__c).put(p.Policy_Status__c, countNuber);
		}else{
			mapPolicy.get(p.Policy_Type__c).put(p.Policy_Status__c, 1);
		}
	}
}*/