objects/HocSinh__c.object
<CustomObject>
    <fields>
        <fullName>GioiTinh__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Nam
Nu</description>
        <label>GioiTinh</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TenHocSinh__c</fullName>
        <label>TenHocSinh</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HocSinh</label>
    <nameField>
        <label>HocSinh Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HocSinhs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MigrationTool/Backup/classes/CapgeminiControl.cls
public with sharing class CapgeminiControl {
	public CapgeminiControl() {
		getData(3,5);
	}

	public void getData(Integer limitNo ,Integer offsetNo){
		Map<ID,HocSinh__c> mapHocSinhNam = new Map<ID,HocSinh__c>();
		List<HocSinh__c> lstHocSinh = [Select Id,Gioitinh__c , TenHocSinh__c from HocSinh__c];
		for(HocSinh__c obj : lstHocSinh){
			if(obj.Gioitinh__c == true){
				mapHocSinhNam.put(obj.ID , obj);
			}
		}
		Map<ID,HocSinh__c> mapHocSinh = new Map<Id,HocSinh__c>([Select TenHocSinh__c from HocSinh__c limit :limitNo offset :offsetNo]);
		System.debug('xxxx lst ' + lstHocSinh.size());
		System.debug('xxxx map ' + mapHocSinh.size());
		System.debug('xxxx mapHocSinhNam ' + mapHocSinhNam.size());

		Integer condition1 = 6;
		Integer condition2 = 9;
		// Phép toán điều kiện 3 ngôi
		System.debug(condition1<condition2?'True':'False');

		String text = '          ';
		System.debug('xxxxx ' + String.isEmpty(text) + ' ' + String.isBlank(text));
	}
}