objects/HocSinh__c.object
<CustomObject>
    <fields>
        <fullName>LopHoc__c</fullName>
        <label>LopHoc</label>
        <referenceTo>LopHoc__c</referenceTo>
        <relationshipLabel>HocSinhs</relationshipLabel>
        <relationshipName>HocSinhs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>HocSinh</label>
    <nameField>
        <label>HocSinh Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HocSinhs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LopHoc__c.object
<CustomObject>
    <fields>
        <fullName>TenLop__c</fullName>
        <label>TenLop</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LopHoc</label>
    <nameField>
        <label>LopHoc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LopHocs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/insertHocSinh.cls
/*
* クラス名:		insert HocSinh Class
* クラス概要:		新入生を挿入
* @created:		2016/04/11 Ksvc Nguyen Hoang Khoi
* @modified:    
*/
public without sharing
class insertHocSinh {
	public HocSinh__c hocSinh
	{get;set;}
	public insertHocSinh() {
		hocSinh = new HocSinh__c();
	}
	 public List<SelectOption> lopSel ;
	public boolean hasError;
	public String tinTest;
	/*
	 * themHocSinh 
	 * 
	 * @param: なし
	 * 
	 * @return: pgref PageReference
	 * 
	 * @created: 2016/04/11 Nguyen Hoang Khoi
	 * 
	 * @modified:
	 */
	
	public PageReference themHocSinh(){
			//validate();
				
				List<ApexPages.Message> errorList = ApexPages.getMessages();
				if(errorList.isEmpty()){
					try{
						insert hocsinh;
						PageReference pgref = new PageReference('/apex/IndexPage');
						pgref.setRedirect(true);	
						return pgref;
				}
				catch(DmlException ex){
					//return nothing 
					
				}	
				catch(Exception e){
					Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, e.getMessage()));
				}
				}
	return null;				
	}

	/*
	 * Lay danh sach lop hoc
	 * 
	 * @param: なし
	 * 
	 * @return: pgref PageReference
	 * 
	 * @created: 2016/04/11 Nguyen Hoang Khoi
	 * 
	 * @modified:
	 */

	public List<SelectOption> getLop(){
		lopSel = new List<SelectOption>();
		try{
				
				List<LopHoc__c> lopList = [SELECT Id, TenLop__c FROM LopHoc__c];
				for (LopHoc__c lop : lopList ){
					SelectOption option = new SelectOption(lop.Id, lop.TenLop__c);
					lopSel.add(option);
					
				}
			}catch(Exception e){
				e.getMessage();
			}  
			return lopSel;
	}

	/*
	 * Direct to Index Page
	 * 
	 * @param: なし
	 * 
	 * @return: pgref PageReference
	 * 
	 * @created: 2016/04/11 Nguyen Hoang Khoi
	 * 
	 * @modified:
	 */
	
	public PageReference backIndexPage(){
		try{
			PageReference pgref = new PageReference('/apex/IndexPage');
			pgref.setRedirect(true);	
			return pgref;
		}catch(Exception e){
			System.debug('=====' +  e.getMessage());
			return null;
		}  			
	}

	public void setError (){
			hasError = true;
			tinTest ='Khoi';
	}
}