objects/HocSinh__c.object
<CustomObject>
    <fields>
        <fullName>Diem1__c</fullName>
        <label>Diem1</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Diem2__c</fullName>
        <label>Diem2</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Diem3__c</fullName>
        <label>Diem3</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DiemTB__c</fullName>
        <formula>(  Diem1__c  +  Diem2__c  +  Diem3__c  )  / 3</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DiemTB</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GioiTinh__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Nam
Nu</description>
        <label>GioiTinh</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HoHocSinhs__c</fullName>
        <label>HoHocSinh</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LopHoc__c</fullName>
        <label>LopHoc</label>
        <referenceTo>LopHoc__c</referenceTo>
        <relationshipLabel>HocSinhs</relationshipLabel>
        <relationshipName>HocSinhs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NgaySinh__c</fullName>
        <label>NgaySinh</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TenHocSinh__c</fullName>
        <label>TenHocSinh</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HocSinh</label>
    <nameField>
        <label>HocSinh Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HocSinhs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LopHoc__c.object
<CustomObject>
    <label>LopHoc</label>
    <nameField>
        <label>LopHoc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LopHocs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MigrationTool/Backup/classes/DetailStudent.cls
/*
* クラス名:		Detail Student Class
* クラス概要:		新入生を挿入
* @created:		2016/04/11 Ksvc Nguyen Hoang Khoi
* @modified:    
*/
public with sharing class DetailStudent {
	 public HocSinh__c hs {get;set;}
	public HocSinh__c hocsinh {get;set;}
	public String hsId {get; set;}
	public DetailStudent() {
		hs = new HocSinh__c();
         hsId = ApexPages.CurrentPage().getParameters().get('hsId');
		 hocsinh = [select HoHocSinhs__c,TenHocSinh__c,GioiTinh__c,NgaySinh__c,Diem1__c,Diem2__c,Diem3__c,DiemTB__c,LopHoc__c  from HocSinh__c where id =: hsId];
	}

	/*
	 * Return Index Page
	 * 
	 * @param: なし
	 * 
	 * @return: なし
	 * 
	 * @created: 2016/04/11 Nguyen Hoang Khoi
	 * 
	 * @modified:
	 */
	public PageReference backIndexPage(){
		try{
			PageReference pgref = new PageReference('/apex/IndexPage');
	    	pgref.setRedirect(true);	
			return pgref;
		}catch(Exception e){
			System.debug('=====' +  e.getMessage());
			return null;
		}  			
    }

    /*
	 * Direct to Update Page
	 * 
	 * @param: なし
	 * 
	 * @return: なし
	 * 
	 * @created: 2016/04/11 Nguyen Hoang Khoi
	 * 
	 * @modified:
	 */
     public PageReference updateStudent(){
		try{
			PageReference pgref = new PageReference('/apex/UpdatePage?hsId=' + hsId);
	    	pgref.setRedirect(true);	
			return pgref;
		}catch(Exception e){
			System.debug('=====' +  e.getMessage());
			return null;
		} 
    }

    /*
	 * Delete Student and return IndexPage
	 * 
	 * @param: なし
	 * 
	 * @return: なし
	 * 
	 * @created: 2016/04/11 Nguyen Hoang Khoi
	 * 
	 * @modified:
	 */
      public PageReference deleteHocSinh(){
		try{
			if(hsId!=null){
			List<HocSinh__c> existing = [Select Id From HocSinh__c
			where Id =: hsId];
			delete existing;}
			else{
				Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Không thể Delete.'));
			}

			PageReference pgref = new PageReference('/apex/IndexPage');
	    	pgref.setRedirect(true);	
			return pgref;
		}catch(Exception e){
			System.debug('=====' +  e.getMessage());
			return null;
		} 
    }
    
}