objects/HocSinh__c.object
<CustomObject>
    <fields>
        <fullName>DiemTB__c</fullName>
        <formula>(  Diem1__c  +  Diem2__c  +  Diem3__c  )  / 3</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DiemTB</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GioiTinh__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Nam
Nu</description>
        <label>GioiTinh</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TenHocSinh__c</fullName>
        <label>TenHocSinh</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HocSinh</label>
    <nameField>
        <label>HocSinh Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HocSinhs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/StudentClassCI.cls
public with sharing class StudentClassCI {
	public HocSinh__c student;
	public Map<Id,HocSinh__c> mapHocSinh {get;set;}

	public StudentClassCI() {
		mapHocSinh = new Map<Id,HocSinh__c>();
		student = getStudent();
		mapHocSinh = getMapHocSinh();
	}

	public HocSinh__c getStudent(){
		HocSinh__c stu = [Select Id, Name from HocSinh__c limit 1];
		return stu;
	}

	public Map<Id,HocSinh__c> getMapHocSinh(){
		Map<Id,Hocsinh__c> mapObj = new Map<Id,Hocsinh__c>();
		try{
			List<Hocsinh__c> hocSinh = [Select Id,TenHocSinh__c,GioiTinh__c,DiemTB__c from Hocsinh__c];
			mapObj.putAll(hocSinh);
		}catch(QueryException ex){
			System.debug('xxxxx ' + ex);
		}
		return mapObj;
	}
}