objects/HocSinh__c.object
<CustomObject>
    <fields>
        <fullName>HoHocSinhs__c</fullName>
        <label>HoHocSinh</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LopHoc__c</fullName>
        <label>LopHoc</label>
        <referenceTo>LopHoc__c</referenceTo>
        <relationshipLabel>HocSinhs</relationshipLabel>
        <relationshipName>HocSinhs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>HocSinh</label>
    <nameField>
        <label>HocSinh Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HocSinhs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LopHoc__c.object
<CustomObject>
    <label>LopHoc</label>
    <nameField>
        <label>LopHoc Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LopHocs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StudentClassCITest.cls
@isTest
private class StudentClassCITest
{
	private static HocSinh__c hosSinhObj;
	private static LopHoc__c lopTest;

	static{
		lopTest = createLop();
		hosSinhObj = createStudent(lopTest.Id);
	}

	private static HocSinh__c createStudent(String lopID) {
		HocSinh__c acc = new HocSinh__c(HoHocSinhs__c ='Account Test',LopHoc__c = lopID);
		insert acc;
		return acc;
	}

	private static LopHoc__c createLop(){
		LopHoc__c lopCreate = new LopHoc__c(Name ='Test Class');
		insert lopCreate;
		return lopCreate;
	}

	static testMethod void testGetStudent() {
		StudentClassCI stuCI = new StudentClassCI();
		stuCI.getStudent();
	}
}